server:
  port: 8087
  servlet:
    session:
      timeout: 18000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seedcup?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: hemu3239

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379

  session:
    redis:
      flush-mode: on_save
      namespace: spring:session

swagger:
  enabled: true
  version: 0.1
  title: 种子杯后台接口文档
  description: 重构中

logging:
  level:
    root: info
  file:
    name: log/spring_log.log